# vim: set filetype=bash

alias RP="   RAILS_ENV=production"
alias RS="   RAILS_ENV=staging"
alias RT="   RAILS_ENV=test"
alias b="    bundle"
alias be="   bundle exec"
alias rs="   rails s"
alias rc="   rails c"
alias rdc="  DATABASE_HOST=127.0.0.1 DATABASE_USERNAME=postgres DATABASE_PASSWORD=password DATABASE_NAME=light-tracker-api_postgres"
alias rcd="  railsd && rails c"
alias rr="   rails routes"
alias bake=" bundle exec rake"
alias rgm="  rails g migration "
alias rdbm=" rails db:migrate"
alias rdbc=" rails db:create"
alias rdbr=" rails db:rollback"
alias rdbs=" rails db:seed"
alias rdbR=" rails db:drop db:create db:migrate"
alias fixdb="rails db:drop db:create db:migrate db:seed"
alias cop="  bundle exec rubocop --autocorrect"
alias bspec="bundle exec rspec"
alias s="    bundle exec rspec"
alias hs="   HEADLESS=false bundle exec rspec"

alias rails_clear_queues="rc && Sidekiq::Queue.all.each(&:clear)"

